export const GAME_CONSTANTS = {
  MIN_BET_CENTS: 100,
  MAX_BET_CENTS: 100000,
  MIN_BET: 1.00,
  MAX_BET: 1000.00,
  BETTING_DURATION_MS: 10000,
  INITIAL_MULTIPLIER: 1.00,
  WS_RECONNECT_DELAY_MS: 2000,
  WS_MAX_RECONNECT_ATTEMPTS: 10,
} as const;

export const BET_LIMITS = {
  min: GAME_CONSTANTS.MIN_BET.toFixed(2),
  max: GAME_CONSTANTS.MAX_BET.toFixed(2),
} as const;
