'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Shield } from 'lucide-react';
import { useRoundHistory } from '@/hooks/useRoundHistory';
import RoundHistoryTable from '../../components/round-history/RoundHistoryTable';
import VerificationModal from '../../components/round-history/VerificationModal';

export default function RoundHistoryPage() {
  const [page, setPage] = useState(1);
  const [verifyRoundId, setVerifyRoundId] = useState<string | null>(null);
  const { data, isLoading } = useRoundHistory({ page, limit: 20 });

  const rounds = data?.data ?? [];
  const meta = data?.meta;

  return (
    <div className="container mx-auto px-4 py-6 space-y-6">
      {/* Back link */}
      <Link
        href="/games"
        className="inline-flex items-center gap-2 text-sm font-terminal text-text-muted hover:text-primary transition-colors"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Game
      </Link>

      {/* Provably Fair banner */}
      <div className="panel-cyber p-4 flex items-center gap-3">
        <Shield className="w-5 h-5 text-primary shrink-0" />
        <p className="text-sm font-terminal text-text-muted">
          All results are generated by a Provably Fair algorithm. Verify any round using the seed and hash.
        </p>
      </div>

      {/* Table */}
      <div className="panel-cyber rounded-lg overflow-hidden">
        <RoundHistoryTable
          rounds={rounds}
          isLoading={isLoading}
          onVerify={setVerifyRoundId}
          emptyMessage="No rounds found"
        />
      </div>

      {/* Pagination */}
      {meta && meta.totalPages > 1 && (
        <div className="flex items-center justify-center gap-4 pt-4">
          <button
            onClick={() => setPage((p) => Math.max(1, p - 1))}
            disabled={page <= 1}
            className="px-4 py-2 text-sm font-terminal text-text-muted border border-border rounded hover:border-primary hover:text-primary disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
          >
            Previous
          </button>
          <span className="text-sm font-terminal text-text-muted">
            {page} / {meta.totalPages}
          </span>
          <button
            onClick={() => setPage((p) => Math.min(meta.totalPages, p + 1))}
            disabled={page >= meta.totalPages}
            className="px-4 py-2 text-sm font-terminal text-text-muted border border-border rounded hover:border-primary hover:text-primary disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
          >
            Next
          </button>
        </div>
      )}

      {/* Verification Modal */}
      {verifyRoundId && (
        <VerificationModal
          roundId={verifyRoundId}
          onClose={() => setVerifyRoundId(null)}
        />
      )}
    </div>
  );
}
