import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import Link from "next/link";
import { ArrowLeft, Shield } from "lucide-react";
import { getQueryClient } from "@/libs/get-query-client";
import { fetchRoundHistory } from "@/libs/server-fetch";
import { RoundHistoryClient } from "./round-history-client";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Round History | Crash Game",
  description: "View past round results and verify fairness",
};

export default async function RoundHistoryPage() {
  const queryClient = getQueryClient();

  await queryClient.prefetchQuery({
    queryKey: ["round-history", 1, 20],
    queryFn: () => fetchRoundHistory({ page: 1, limit: 20 }),
  });

  return (
    <div className="container mx-auto px-4 py-6 space-y-6">
      <Link
        href="/games"
        className="inline-flex items-center gap-2 text-sm font-terminal text-text-muted hover:text-primary transition-colors"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Game
      </Link>

      <div className="panel-cyber p-4 flex items-center gap-3">
        <Shield className="w-5 h-5 text-primary shrink-0" />
        <p className="text-sm font-terminal text-text-muted">
          All results are generated by a Provably Fair algorithm. Verify any
          round using the seed and hash.
        </p>
      </div>

      <HydrationBoundary state={dehydrate(queryClient)}>
        <RoundHistoryClient />
      </HydrationBoundary>
    </div>
  );
}
