_format_version: "3.0"

services:
  - name: games-service
    url: http://games:4001
    routes:
      - name: games-health
        paths: [/games/health]
        strip_path: false
      - name: games-rounds-current
        paths: [/games/rounds/current]
        strip_path: false
      - name: games-rounds-history
        paths: [/games/rounds/history]
        strip_path: false
      - name: games-rounds-verify
        paths: [/games/rounds]
        strip_path: false
      - name: games-bets-me
        paths: [/games/bets/me]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
      - name: games-bet
        paths: [/games/bet]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
      - name: games-bet-cashout
        paths: [/games/bet/cashout]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid

  - name: wallets-service
    url: http://wallets:4002
    routes:
      - name: wallets-health
        paths: [/wallets/health]
        strip_path: false
      - name: wallets-me
        paths: [/wallets/me]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
      - name: wallets-create
        paths: [/wallets]
        strip_path: false
        methods: [POST]
        plugins:
          - name: jwt
            config:
              key_claim_name: kid

consumers:
  - username: keycloak-crash-game
    jwt_secrets:
      - consumer: keycloak-crash-game
        key: lh1voD04tRzMaQxMMZ_Nz15QIgA_xTgHfvQaopRR5IA
        algorithm: RS256
        rsa_public_key: |-
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3FroCKE6yiWldU+FvLxY
          QGNO27gPLHy3qdTalX6lt//pZluApwmwVxgCDdetLPD5EnxKyCN6LBzBu1nfBnNL
          1OtE7xPo0RNYa/kGqeSe3XC063eYTzqz38VkNCMv/REHNwRvhc5mdB2ntAQTGMNm
          GNEbfpwrVSYlra2eCINDcnzOuex/9kq2d4F0pEyYwI4bzScNfUMKE3YFVyD4zl2g
          zLDiOHkntNa7I0hOpSEUQ/Xh4wh66A+W+HBP6ryQGo9UQ8Q1A8VGKtv4/FBH+Jdj
          RbRteqpisv5PYyHkgKuhF+u+FAS4QXpFjVjmMvZ2Qa6H7EkUiemWte9bUWLiDc2l
          gwIDAQAB
          -----END PUBLIC KEY-----
