_format_version: "3.0"

services:
  - name: games-service
    url: http://games:4001
    plugins:
      - name: cors
        config:
          origins: ["http://localhost:3000", "http://localhost:5173"]
          methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          headers: ["Accept", "Authorization", "Content-Type", "Origin"]
          exposed_headers: ["Content-Length", "Content-Type"]
          credentials: true
          max_age: 3600
    routes:
      - name: games-health
        paths: [/games/health]
        strip_path: false
      - name: games-rounds-current
        paths: [/games/rounds/current]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
              anonymous: skip-auth
      - name: games-rounds-history
        paths: [/games/rounds/history]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
              anonymous: skip-auth
      - name: games-rounds-verify
        paths: [/games/rounds]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
              anonymous: skip-auth
      - name: games-bets-me
        paths: [/games/bets/me]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
              anonymous: skip-auth
      - name: games-bet
        paths: [/games/bet]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
              anonymous: skip-auth
      - name: games-bet-cashout
        paths: [/games/bet/cashout]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
              anonymous: skip-auth
      - name: games-websocket
        paths: [/games]
        strip_path: true
        protocols: [http, https]
        plugins:
          - name: cors
            config:
              origins: ["http://localhost:3000", "http://localhost:5173", "http://localhost:8000"]
              methods: ["GET", "POST", "OPTIONS"]
              headers: ["Accept", "Authorization", "Content-Type", "Origin", "X-Requested-With"]
              exposed_headers: ["*"]
              credentials: true
              max_age: 3600
      - name: games-websocket-root
        paths: [/socket.io]
        strip_path: false
        protocols: [http, https]
        plugins:
          - name: cors
            config:
              origins: ["http://localhost:3000", "http://localhost:5173"]
              methods: ["GET", "POST", "OPTIONS"]
              headers: ["Accept", "Authorization", "Content-Type", "Origin"]
              exposed_headers: ["Content-Length", "Content-Type"]
              credentials: true
              max_age: 3600

  - name: wallets-service
    url: http://wallets:4002
    plugins:
      - name: cors
        config:
          origins: ["http://localhost:3000", "http://localhost:5173"]
          methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          headers: ["Accept", "Authorization", "Content-Type", "Origin"]
          exposed_headers: ["Content-Length", "Content-Type"]
          credentials: true
          max_age: 3600
    routes:
      - name: wallets-health
        paths: [/wallets/health]
        strip_path: false
      - name: wallets-me
        paths: [/wallets/me]
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
              anonymous: skip-auth
      - name: wallets-create
        paths: [/wallets]
        strip_path: false
        methods: [POST]
        plugins:
          - name: jwt
            config:
              key_claim_name: kid
              anonymous: skip-auth

consumers:
  - username: keycloak-crash-game
    jwt_secrets:
      - key: Cd1rriM6-PuedGB37Cal69lVyQt3TyX66KHz18LAo5k
        algorithm: RS256
        rsa_public_key: |-
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyZFSSxyoP6azbUfABJa1
          KVwOdJ/dTRqwsEqZfMAYK5vfLseTyGIVtfr7AHg1PbRESgDUezs+aDMikaPIX6VY
          5LMwtpW1TIVOcmkkA6yTJgD3Qk7OaSbpn/FpBdi66v4l5Ail4fDdjsIoFnKAxlI2
          UBTI3TgNjXtIMJsKyr34t82QVT0c1mkOiRWVmJGLm/YfU1/Fia9pt6vF3O6BeEyX
          v3e9k2iXINT2deWCvwO9xYFetAe2392/7Pn9oVAhIYnTuC/bVdpY3FKoCXXYz7XZ
          dBIQaBxTq/+HqrKRn9PRsjIdsUe0r0Zl/MJ/FxsBS4W5ICXMw6MAL5LNHvZKibmm
          oQIDAQAB
          -----END PUBLIC KEY-----
  - username: skip-auth
    jwt_secrets:
      - key: m-U9iZ4MfvXDo3DZwPwCRuNRygY8sdyOOf1zRje_TwU
        algorithm: RS256
        rsa_public_key: |-
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4aQfhMoZR8/fC5pyI0lO
          lEsLjZGHW6+qExaAvcdTiJaUVc+QcoRJESex1VhW/YReEW61WWMe2gNHH+nSDFBN
          ablxfKIl3OiDGo/Iqsh7d5NOX4IV0RrEZZyUhvyH16eJTZhI4ho4vNbKHQJKm5Lh
          TgL6gLUYfwq1/n6Zql6WzV3UnwDzXp7QTEQWCEdoakJOfqvMEWmCY0WT+Zm9zub9
          BtF/I1oDEKxiWX/h6thRtLRX+gb4hItU75fMSvf6HpzZnF2hlrc7fKsGcBSkiVSv
          YQwfl7/CwI4huDfk7DYBSqOwsj70lCySNR8dAQ+FXYZLMJ7kMdiRdSlbZcQSO9TH
          gQIDAQAB
          -----END PUBLIC KEY-----
